### ISSUE TITLE
Windows overlap the bar

### ISSUE THREAD

**Issue by simply-silver** [danielnehrig/polybar-powerline#1]
![image](https://user-images.githubusercontent.com/44275901/98160576-00186280-1ea4-11eb-82b4-e00ea7df3666.png)

Immediately after installing, I noticed that it does not add space between the bar and other windows. Is there any fix?

**Comment by danielnehrig** [comment]
fixed in 
https://github.com/danielnehrig/polybar-powerline/commit/f280241ba4ec916cca2e71ec0188372971798952
