### ISSUE TITLE
Dropping unmatched character poly bar not rendering correctly

### ISSUE THREAD

**Issue by PhantomCloak** [danielnehrig/polybar-powerline#3]
I tested 2 different box with i3 setup icons not properly loaded and got these errors I thought it caused by fonts but even all dependencies are installed nothing changes  

It looks like this
[
![image](https://user-images.githubusercontent.com/34552014/98371197-d51d4280-204c-11eb-9acd-1b9f09ed9dc8.png)
](url)  

Setup that I tested

i3-gaps 4.18.3-1
polybar 3.4.3-2
picom-git 1430_8.rc2.21.gfd6ff82_2020.06.06-1

Dependencies Installed

nerd-fonts-complete 2.1.0-3
ttf-material-design-icons 4.0.0-1

Output
```
warn: pulseaudio: using default sink alsa_output.usb-C-Media_Electronics_Inc._USB_PnP_Sound_Device-00.analog-stereo
warn: The config parameter `module/wireless-network.udspeed-minwidth` is deprecated, use `module/wireless-network.%downspeed:min:max% and %upspeed:min:max%` instead.
error: Disabling module "wireless-network" (reason: Invalid network interface "wlp3s0")
warn: X resource "Xft.dpi" not found, using defined fallback value "-1"
warn: Ignoring restack of i3 window (not needed when `override-redirect = false`)
warn: Dropping unmatched character 󱐝 (U+f141d)
warn: Dropping unmatched character 󱐝 (U+f141d)
warn: Dropping unmatched character 󱐝 (U+f141d)
warn: Dropping unmatched character 󱐝 (U+f141d)
warn: Dropping unmatched character 󱐝 (U+f141d)
warn: Dropping unmatched character 󱐝 (U+f141d)
```

**Comment by danielnehrig** [comment]
Looks like you have the wrong material icons
i used these ones https://material.io/resources/icons/?style=baseline

**Comment by danielnehrig** [comment]
updated readme in 43d2d582aab723801e69ac7439512c9ca2d5867c
